#!/bin/bash
# NierTerm default bashrc - minimal and clean

# Only run for interactive shells
[[ $- != *i* ]] && return

# Simple abbreviated path PS1 (shows last 2 dirs)
# Format: user@host:~/.../dir$
PS1='\[\033[1;32m\]\u@\h\[\033[0m\]:\[\033[1;34m\]\W\[\033[0m\]\$ '

# Terminal settings
export TERM=xterm-256color

# History settings
HISTSIZE=10000
HISTFILESIZE=20000
HISTCONTROL=ignoreboth:erasedups
shopt -s histappend

# Basic aliases
alias ls='ls --color=auto'
alias ll='ls -alF --color=auto'
alias la='ls -A --color=auto'
alias grep='grep --color=auto'
alias q='exit'
alias ..='cd ..'
alias ...='cd ../..'

# Safety aliases
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'

# Path additions
export PATH="$PATH:$HOME/.local/bin:$HOME/.cargo/bin"

# Tab completion
bind 'TAB: menu-complete'
bind 'set show-all-if-ambiguous on'
bind 'set completion-ignore-case on'
